### ISSUE TITLE
Use a different VLM

### ISSUE THREAD

**Issue by tcourat** [likyoo/SemiCD-VL#2]
Hi,

Thanks for you work.

Have you tried to use a different VLM, and especially a "remote sensing" VLM such as [RemoteCLIP](https://arxiv.org/abs/2306.11029) instead of a general one like APE ?

**Comment by likyoo** [comment]
Yes, we tried them. But sadly, they don't even perform better than CLIP.

**Comment by likyoo** [comment]
@tcourat We evaluated the performance of remote sensing CLIP on segmentation tasks in [SegEarth-OV](https://likyoo.github.io/SegEarth-OV/), which may be a reference.
